language: python
env:
  # No 1.7 due to ImportError: cannot import name captured_stdout
  # - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.8.1
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.8.3
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.8.5
  - DJANGO_VERSION=1.8.6
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.8.9
  - DJANGO_VERSION=1.8.10
  - DJANGO_VERSION=1.8.11
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.9.1
  - DJANGO_VERSION=1.9.2
  - DJANGO_VERSION=1.9.3
  - DJANGO_VERSION=1.9.4
python:
  # Django 1.9 requires Python 2.7, 3.4, or 3.5.
  # Since Django 1.8, weâ€™ve dropped support for Python 3.2 and 3.3, and added support for Python 3.5.
  # No 2.7 due to TypeError: super() takes at least 1 argument (0 given)
  # - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  # - "3.6-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements-travisci.txt
# command to run tests
script: python manage.py test
